name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Set version
        run: |
          export VERSION=${{ steps.previoustag.outputs.tag }}
      - name: Setup tools
        run: sudo apt-get install pandoc
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Build
        run: VERSION="${{ steps.previoustag.outputs.tag }}" make all
